### ISSUE TITLE
https://space.greyh.cn

### ISSUE THREAD

**Issue by huihong3** [ccknbc-actions/moments#17]
**标题请书写你的链接，不要写其他内容**

```yaml
# 显示名称
name: 灰鸿的空间

# 跳转地址
link: https://space.greyh.cn

# 你的头像
avatar: https://gitee.com/huihongyhy/imgbed/raw/master/img/avatar.png

# 你的描述
descr: 一名科技爱好者的空间

#------------------------------#
#       以下字段为选填字段       #

# 边框及鼠标悬停的背景颜色，允许设置渐变色
--primary-color: linear-gradient(to bottom, #232526, #414345)

# 昵称和描述颜色，不允许设置渐变色
--namecolor: 

# 鼠标悬停的昵称和描述颜色，不允许设置渐变色
--namecolorHover: 

# 边框大小
border-width: 0px

# 边框样式
border-style: solid

# 鼠标悬停头像旋转角度
--primary-rotate: 0deg

# 边框动画 参考 https://developer.mozilla.org/zh-CN/docs/Web/CSS/animation
# 内置动画：borderFlash（边框闪现）、link_custom1(跑马灯)、link_custom(主颜色呼吸灯)
animation: borderFlash 0s infinite alternate

# 头像动画 参考 https://developer.mozilla.org/zh-CN/docs/Web/CSS/animation
# 内置动画：auto_rotate_left（左旋转）、auto_rotate_right（右旋转）
img_animation: auto_rotate_right 0s linear infinite

# 风格 可选项 item 和 card
card_style: card

# 自定义网站截图，当样式为 card 时可以自定义网站截图
screenshot: https://cdn.jsdelivr.net/gh/ccknbc-actions/blogroll@webp/space.greyh.cn.webp
```
